baseURL = 'https://oppenbhaimer.github.io'
languageCode = 'en-us'
title = 'Oppenbhaimer'
theme = 'paper'

# disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  # color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'oppenbhaimer'               # twitter.com/YOUR_TWITTER_ID
  github = 'oppenbhaimer'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Oppenbhaimer'
  bio = "Counterintuitively, I post neither nuclear physics nor Salman Khan content."

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "oppenbhaimer-github-io" # use graph comment (disqus alternative)
  math = true                               # enable KaTeX math typesetting globally

[permalinks]
  posts = '/:year/:title'

